### ISSUE TITLE
Missing U+00B7("MIDDLE DOT") in Regular and Oblique

### ISSUE THREAD

**Issue by jbt** [chrissimpkins/Hack#27] opened 2015-08-29 11:59 UTC
Looks like the Bold and BoldOblique styles both include U+00B7 but the Regular and Oblique don't. Would be great if this could be added as it's the default character used by Atom to signify invisible whitespace, and the missing glyph causes it to use a fallback that messes up alignment

**Comment by chrissimpkins** [comment] 2015-08-29 12:02
Thanks for reporting this James. I should be able to get this fixed this weekend.

**Comment by lem8r** [comment] 2015-08-30 09:46
+1
Same problem with Atom

**Comment by chrissimpkins** [comment] 2015-08-30 12:30
Thanks for letting me know Bogdan.  This is definitely a priority.

**Comment by TPS** [comment] 2015-08-31 17:05
Solving #46 would fix this & vice versa, it looks like.

**Comment by chrissimpkins** [comment] 2015-08-31 18:55
@TPS Hope to have a build that you can try this evening.  U+00B7 was in these sets but without a glyph and with a wider em box than the rest of the set.  Seems to be an issue with the transition from the design editor to my build editor.  I agree, I think this explains the extra spacing issue in #46.

**Comment by chrissimpkins** [comment] 2015-08-31 22:34
v2.011 is a test build of the ttf files that includes the middle dot glyph in all sets and adjustment in the width of the em box of this glyph that (hopefully) caused the issues reported here and in #46. 

**Download Links**

[Regular](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Regular-2_011.ttf?raw=true)
[Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-RegularOblique-2_011.ttf?raw=true)
[Bold](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-Bold-2_011.ttf?raw=true)
[Bold Oblique](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/Hack-BoldOblique-2_011.ttf?raw=true)

Let me know if this addresses these issues.

**Comment by kenjij** [comment] 2015-08-31 23:21
Just confirming that the issue is same with TextMate 2 as well in case someone stubbles upon here; missing space char when using "Regular", but "Bold" works.

With v2.011 test build, "Regular" works as expected.

@chrissimpkins great font, I like it, thanks!

**Comment by chrissimpkins** [comment] 2015-08-31 23:30
thanks much for the feedback @kenjij!  that is very helpful

**Comment by jbt** [comment] 2015-09-01 06:46
Test build looks good for me in Atom :+1:

**Comment by GU5TAF** [comment] 2015-09-01 09:10
Works for me in atom as well, good job!

**Comment by chrissimpkins** [comment] 2015-09-08 00:36
Thanks so much for the issue report and tests.  The fix for this issue is now live in the master branch as version 2.013.  Closing this issue as fixed.

**Closed by chrissimpkins** 2015-09-08 00:36 UTC
Labels: Character Set issue
