### ISSUE TITLE
Line spacing could be optimised further

### ISSUE THREAD

**Issue by jpluimers** [chrissimpkins/Hack#146] opened 2015-10-31 08:06 UTC
I'm using https://github.com/chrissimpkins/Hack/releases/download/v2.015/Hack-v2_015-ttf.zip

Line spacing could be optimised further. Lucida Console displays 63 lines which is 15% more than Hack that displays 55 lines. 

With Lucida Console, the lines really touch each other: look at the lower and upper stems in this code fragment at lines 49/50:

      fmShareCompat    = $0000 platform; // DOS compatibility mode is not portable
      fmShareExclusive = $0010;

This is from a Windows 8.1 doing an RDP connection with 32-bit colour depth to my development machine that runs Windows 7 that runs Delphi 2007 but I have similar results in Visual Studio 2013 ([Hack](https://www.dropbox.com/s/9qekxo0pc07w7yb/20151031-VS2013-Hack%4010points.png?dl=0) vs [Lucida Console](https://www.dropbox.com/s/i0q0kn34c11p7dj/20151031-VS2013-LucidaConsole%4010points.png?dl=0):

# Hack @ 10 points

[![Hack @ 10 points](https://www.dropbox.com/s/ey7rzgiuzrwpv9d/20151031-SysUtils-Hack%4010points.png?raw=1)](https://www.dropbox.com/s/ey7rzgiuzrwpv9d/20151031-SysUtils-Hack%4010points.png?dl=0)

# Lucida Console @ 10 points
[![Lucida Console @ 10 points](https://www.dropbox.com/s/9w2nop21070k3dc/20151031-SysUtils-LucidaConsole%4010points.png?raw=1)](https://www.dropbox.com/s/9w2nop21070k3dc/20151031-SysUtils-LucidaConsole%4010points.png?dl=0)

**Comment by burodepeper** [comment] 2015-10-31 08:21
Hallo meneer @jpluimers ;)

I'll stick to English for the 'official' part.
I am currently working on the usability aspects of Hack, and the default line-height plays a major role in general readability. Besides a matter of personal taste, it is also a matter of identity of the typeface, and I'm afraid we can't service everybody in that aspect. Please note the significant difference in design in the ratio between x-height vs ascender and descenders in your two examples. It is something however that we will look into.

**Comment by chrissimpkins** [comment] 2015-10-31 10:54
Thank you very much for the suggestion Jeroen.  I agree with David's (@burodepeper) comments above. Our goal is not _necessarily_ to fit the most code in a single view that is humanly possible.  We must balance the legibility of the source with the goal to view more of it.  There are users in other issue reports who have requested that the line spacing be further expanded to provide additional whitespace to address the opposite end of this spectrum.  There is a balance here and David is leading the work to base our usability decisions on more objective grounds.  You will be hearing a great deal more about this down the road when we begin to generate proposals for typeface changes based upon these analyses that are in progress.

**Comment by jpluimers** [comment] 2015-11-04 15:58
It would be soooo cool if in addition to font sizes, line spacing would be configurable in one way or the other by the tools I use. Too bad they don't. 

How difficult would it be to build a one-off that have smaller line heights (My knowledge on this is rusty as I've been out of the scalable font industry for like 20 years, but given the work I did for Polyvroom and Mecanorma in the early 90's producing fonts for Monotype and others, it still interests me a lot).

**Comment by chrissimpkins** [comment] 2015-11-04 16:06
simple to create it, the problem is that all vertically aligned glyphs are thrown off.  If you don't have a significant concern about box glyphs and line glyphs at this stage we can try some variants.  we are still working to get those fixed in the main sets...

**Comment by chrissimpkins** [comment] 2015-11-04 16:08
do you have access to a font editor Jeroen?

**Comment by jpluimers** [comment] 2015-11-05 21:16
I've been out of the business for a long long time. Back then it was Ikarus on a MicroVax and Sun based software by an Israeli company. Part of the network was over serial connections, the rest Windows 3.1 with COAX ethernet. If you can help me kick-start: I *am* an experienced software developer and Ops person with Windows and Unix backgrounds.

**Comment by chrissimpkins** [comment] 2015-11-05 23:06
Wondering because we could try to explore what line spacing works for you.   Maybe FontForge?

**Comment by doubleagent** [comment] 2016-01-31 23:21
The Lucida Console line spacing is much too small for my tastes.

**Comment by phantom-code** [comment] 2016-02-11 08:01
Personally, I found Hack's line spacing is close to ideal (I would even prefer to increase it). When line spacing is small, the source code becomes unreadable. I think that suggested optimization will be harmful. If you like line spacing of Lucida Console, then just use it.

**Comment by chrissimpkins** [comment] 2016-02-11 14:03
@phantom-code @doubleagent Thanks for your feedback.  Any changes to the line spacing at this stage would likely be in the form of new variant sets.  I have been tossing around the idea of a script that will modify the OpenType settings for you so that you can create these on your own and at the spacing that you prefer.  The script is not difficult.  The problem is that all vertically aligned glyphs (e.g. the box drawing and block element glyphs) would be out of alignment in these sets.  Will let you know if/when this is available if it is something of interest to explore different line spacing in more detail with the fonts.

**Comment by jpluimers** [comment] 2016-02-13 15:40
Sorry for having been out of touch that long. I've been on a cramped project, but reserved some time in March to devote on open source projects. Please let me know how I can help by then, and I'll try to schedule some time for it. 

The machinery I will have at hand then:
- Mac OS X machine with homebrew, Xcode and any development tools I need
- OpenSuSE Tumbleweed VM on which I can install anything I need
- Windows 8.1 and 10 VMs on which I can install anything I need

Back in the days (early 90s) I was involved in creating scaleable fonts for Mecanorma, but I don't have access to the hardware (MicroVax, table sized digitisers, Sun pizzabox, early Apple Mac and 80386 PCs) or software (Ikarus and some Israelian built custom Sun software), any more. I hope my memory still works well enough for remembering some stuff (hopefully scoring 90 at http://type.method.ac/ helps <g>).

One day I will dig out the source code for https://www.google.com/search?q="dmpfm151.zip" (:

**Comment by chrissimpkins** [comment] 2016-02-13 16:04
@jpluimers :)  love it

Will let you know when we have a script that you can try.  You will be able to execute it with Python directly on the font files.  Should not require anything special.

**Comment by chrissimpkins** [comment] 2016-03-24 12:56
Started work on an application to address this.  It will allow you to easily modify the spacing yourself.  Hope to have a version that you can try in the next several days.  Will post here when available.

**Comment by chrissimpkins** [comment] 2016-03-26 09:30
The initial release of the new line spacing adjustment tool is now available.  Feel free to give it a try and please provide feedback on the tool repository if you encounter any issues.

More details in this new issue report: https://github.com/chrissimpkins/Hack/issues/191

**Comment by chrissimpkins** [comment] 2016-03-29 11:56
Closing issue report now that the line spacing tool is available.  We do not intend to modify the default line spacing at this point.  Please reopen if you need and submit any issues with the tool on that repository.

**Closed by chrissimpkins** 2016-03-29 11:56 UTC
Labels: Design

**Comment by chrissimpkins** [comment] 2016-04-07 12:55
Line spacing shell scripts are now available and automate this within the range 10 - 30% UPM size (in 5 percentage point increments).  Drop the script in a directory with **only** your Hack fonts and execute it.

They are available here:

https://github.com/chrissimpkins/Hack/tree/master/tools/line-spacing

**Comment by jpluimers** [comment] 2018-03-12 10:28
It seems the tool moved, but I could not find the commit it moved in. Did it move to https://github.com/source-foundry/font-line ?

**Comment by chrissimpkins** [comment] 2018-03-12 12:31
@jpluimers If you are looking for the shell script it can be found here https://gist.github.com/chrissimpkins/f39e85f5f157d839e46168de1b61a174 

The underlying tool is the font-line project that you linked above.  Let me know if you have any questions about use.
