### ISSUE TITLE
Missing number sign [U+2116]

### ISSUE THREAD

**Issue by xstee** [chrissimpkins/Hack#114] opened 2015-09-24 09:41 UTC
It will be very nice to add sign №

**Comment by chrissimpkins** [comment] 2015-09-24 11:15
Yes this is definitely possible.  For my own information, how are you using this in source code?

**Comment by jublo** [comment] 2015-09-25 18:00
U+2116

**Comment by chrissimpkins** [comment] 2015-09-25 18:24
Trying to get at whether you are using this in the context of source code and how so that I can look at size and alignment of the glyph relative to other characters.

**Comment by jublo** [comment] 2015-09-25 19:00
Suggesting this one.

![image](https://cloud.githubusercontent.com/assets/6348321/10109643/6e45bea2-63c8-11e5-8088-22aa0839c2d6.png)

**Comment by chrissimpkins** [comment] 2015-09-25 19:08
sorry I am likely not being clear.  what are you positioning that character near?  using it to show version numbers or different use?  I understand the glyph that is being requested.  I'm interested in how it is being used with the font.  may be outside of source code which is fine as well.  wanted to optimize within context of the request if this is source code specific.

**Comment by xstee** [comment] 2015-09-28 07:16
Chris,

I'm from Russia and here we use '№' instead of '#'. Where? Everywhere. For
example, now I'm working on document automation system. Each order must
have a number. Like here:
http://noo-ws.net/talk/wp-content/uploads/2014/03/art_law_samohina_doc_1.gif

I use number sign in source code only as string literal. Like this:
printf('Order №%d', orderNumber);

**Comment by chrissimpkins** [comment] 2015-09-28 10:26
Perfect.  That is very helpful.  Tying to work it into a release in the next couple of weeks.   Thanks for your feedback.

**Comment by chrissimpkins** [comment] 2015-09-28 17:15
@jublo began work on this glyph.  Hope to have a test build out soon that you can try to provide feedback before we release it.  It is a wide glyph and there is not much that we can do with spacing.  Currently working on the position of the `O` component of the glyph to determine what looks best.  

Will update here.

**Comment by chrissimpkins** [comment] 2015-09-30 01:07
@jublo I took a look at the glyphs in all four sets.  We are constrained by the fixed width of the fonts, but I wonder if we can take a bit of the counter out of the O portion and add more width to the N portion of the glyph.  When I take it down to small text sizes, the N component of the glyph starts to get very crowded and it is difficult to make out the strokes of the N.  We may even be able to leave the O component as is and move the right vertical stroke of the N to the right so that there is more space within that glyph component and less between the two glyph components.  Will need to see what that does to the angled stroke on the glyph and look at how it renders to the pixel grid at smaller sizes.  We can create a few iterations and build them so that we can take a look outside of the font editors.

@xstee Leonid we will let you know when there are builds available if you'd be interested in helping us test this.

**Comment by chrissimpkins** [comment] 2015-09-30 01:59
@jublo better yet, maybe we use the left side of the box for the N component instead.  Something along these lines? (see rendering of the glyph at smaller sizes at screen bottom in each screenshot):
### Left sidebearing decreased, N widened, O component slightly right aligned
![no-open](https://cloud.githubusercontent.com/assets/4249591/10182660/9b8d0cec-66f4-11e5-9520-522af4c32749.png)

![no-closed](https://cloud.githubusercontent.com/assets/4249591/10182662/9f036b78-66f4-11e5-8236-9040027db735.png)

### Original Design for Comparison

![numero-old](https://cloud.githubusercontent.com/assets/4249591/10182687/01955c56-66f5-11e5-98d6-dd3312d320cf.png)

This glyph will come after a space character so the left sidebearing is less important than the right.  We will need to take a look at this next to numerals.

**Comment by jublo** [comment] 2015-09-30 11:28
In the Russian sample, the sign was followed by a space, like `№ 1`. I fully support your edit of the original design.

**Comment by chrissimpkins** [comment] 2015-09-30 11:54
Let's move ahead with these changes.

**Comment by jublo** [comment] 2015-10-07 09:20
Preparing PR with this diff for `Regular`:

<img width="368" alt="bildschirmfoto 2015-10-07 um 11 19 11" src="https://cloud.githubusercontent.com/assets/6348321/10333602/4d5d3b68-6ce5-11e5-85fa-cd1863b351af.png">

**Comment by chrissimpkins** [comment] 2015-10-07 16:40
merged.  thanks @jublo.  is there a bold version in that merge as well?

**Comment by jublo** [comment] 2015-10-07 17:43
Yup, there was—both in TTF and UFO.  Have you found it?

![](https://cloud.githubusercontent.com/assets/6348321/10335609/43b901a2-6cf2-11e5-95a8-8f85483063fd.png)

**Comment by chrissimpkins** [comment] 2015-10-12 03:44
A new test build (v2.016) is now available with this new glyph.  Please give it a try and let us know what you think.

[Hack-Regular.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Regular.ttf?raw=true)
[Hack-Bold.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Bold.ttf?raw=true)
[Hack-Italic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-Italic.ttf?raw=true)
[Hack-BoldItalic.ttf](https://github.com/chrissimpkins/Hack/blob/development/build/test_builds/2_016/Hack-BoldItalic.ttf?raw=true)

**Comment by xstee** [comment] 2015-10-13 08:22
Chris, it's awesome! Thanks a lot.

Everything is well but one thing. Is this a bug?
Take a look at screenshot, please:
![2015-10-13 13-19-21 latin c and c beautychel ld - sublime text unregistered](https://cloud.githubusercontent.com/assets/8166186/10449486/b950359e-71b5-11e5-9721-0a0f76082def.png)

**Comment by jublo** [comment] 2015-10-13 08:36
@xstee That’s not a bug, but intended—in classic monospace fonts, lots of developers have problems distinguishing between Latin `C` and Cyrillic `Es` letters, so we decided to make a clear difference.

We’re eager to get to know your opinion!  …But please post it in its corresponding issue #22, will you?

**Comment by xstee** [comment] 2015-10-13 09:10
Consider this issue as 'done'. May I close it?

**Comment by chrissimpkins** [comment] 2015-10-13 11:16
We are doing some testing this week and will close it when completed.  Thanks!

**Comment by chrissimpkins** [comment] 2015-11-04 04:32
These changes were included in the v2.017 release

**Closed by chrissimpkins** 2015-11-04 04:32 UTC
Labels: Character Set issue
